// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RETURNCALL_MESSAGING_H_
#define FLATBUFFERS_GENERATED_RETURNCALL_MESSAGING_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
// static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
//               FLATBUFFERS_VERSION_MINOR == 2 &&
//               FLATBUFFERS_VERSION_REVISION == 10,
//              "Non-compatible flatbuffers version included");

namespace Messaging {

struct ReturnCall;
struct ReturnCallBuilder;

struct ReturnCall FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReturnCallBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNIQUE_ID = 4,
    VT_LENGTH = 6,
    VT_RETURN_VALUE = 8
  };
  uint8_t unique_id() const {
    return GetField<uint8_t>(VT_UNIQUE_ID, 0);
  }
  uint16_t length() const {
    return GetField<uint16_t>(VT_LENGTH, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *return_value() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_RETURN_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_UNIQUE_ID, 1) &&
           VerifyField<uint16_t>(verifier, VT_LENGTH, 2) &&
           VerifyOffset(verifier, VT_RETURN_VALUE) &&
           verifier.VerifyVector(return_value()) &&
           verifier.EndTable();
  }
};

struct ReturnCallBuilder {
  typedef ReturnCall Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unique_id(uint8_t unique_id) {
    fbb_.AddElement<uint8_t>(ReturnCall::VT_UNIQUE_ID, unique_id, 0);
  }
  void add_length(uint16_t length) {
    fbb_.AddElement<uint16_t>(ReturnCall::VT_LENGTH, length, 0);
  }
  void add_return_value(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> return_value) {
    fbb_.AddOffset(ReturnCall::VT_RETURN_VALUE, return_value);
  }
  explicit ReturnCallBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReturnCall> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReturnCall>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReturnCall> CreateReturnCall(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t unique_id = 0,
    uint16_t length = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> return_value = 0) {
  ReturnCallBuilder builder_(_fbb);
  builder_.add_return_value(return_value);
  builder_.add_length(length);
  builder_.add_unique_id(unique_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReturnCall> CreateReturnCallDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t unique_id = 0,
    uint16_t length = 0,
    const std::vector<uint8_t> *return_value = nullptr) {
  auto return_value__ = return_value ? _fbb.CreateVector<uint8_t>(*return_value) : 0;
  return Messaging::CreateReturnCall(
      _fbb,
      unique_id,
      length,
      return_value__);
}

inline const Messaging::ReturnCall *GetReturnCall(const void *buf) {
  return ::flatbuffers::GetRoot<Messaging::ReturnCall>(buf);
}

inline const Messaging::ReturnCall *GetSizePrefixedReturnCall(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Messaging::ReturnCall>(buf);
}

inline bool VerifyReturnCallBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Messaging::ReturnCall>(nullptr);
}

inline bool VerifySizePrefixedReturnCallBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Messaging::ReturnCall>(nullptr);
}

inline void FinishReturnCallBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Messaging::ReturnCall> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedReturnCallBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Messaging::ReturnCall> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Messaging

#endif  // FLATBUFFERS_GENERATED_RETURNCALL_MESSAGING_H_
